# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2FPN7ccz7_Kl0g_BeGWQzoLYdK6VF-W
"""

import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("heart_preprocesing.csv")

X = df.drop(columns=['target'])
   y = df['target']

   X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

with mlflow.start_run():
        model = LogisticRegression(max_iter=1000)
        model.fit(X_train, y_train.values.ravel())

accuracy = model.score(X_test, y_test.values.ravel())
print(f"Training Selesai Berhasil! Akurasi Model: {accuracy:.4f}")

!pip install pyngrok
import subprocess
import time
from pyngrok import ngrok

!pkill -f mlflow
!pkill -f ngrok

!mlflow ui --host 0.0.0.0 --port 5000 &

print("Starting MLflow UI in background...")
subprocess.Popen(["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"])
time.sleep(5) # Give MLflow UI some time to start
print("MLflow UI started.")

ngrok.set_auth_token("3EMHx3r617bPo7Lwg1wVd3YE100_3b8gx37XEYUvW35TBWcca")

print("Sedang menghubungkan Ngrok ke Port 5000...")
public_url = ngrok.connect(5000)

print("\n=== SUKSES! ===")
print("Klik link di bawah ini untuk membuka MLflow UI kamu:")
print(public_url.public_url)