name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      # SOLUSI ERROR MAINTENANCE MODE: Mengizinkan penyimpanan local backend di GitHub runner
      MLFLOW_ALLOW_FILE_STORE: true 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas matplotlib scikit-learn joblib mlflow

    - name: Run MLflow Project
      run: |
        # Masuk ke folder tempat MLproject berada dan jalankan run otomatis sesuai modul
        cd MLProject
        mlflow run . --env-manager=local
