name: Machine Learning Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        # Baris cache: 'pip' sudah dihapus di sini agar tidak memicu error

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Script hanya akan menginstal requirements jika filenya memang ada
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install Flask prometheus_client requests pandas scikit-learn

    - name: Run Verification
      run: |
        python -m py_compile prometheus_exporter.py
